# Generated by Django 5.0.1 on 2026-01-27 10:29

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("documents", "0002_auditflag_compliancecheck_journalentry_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegulatoryReference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "regulator",
                    models.CharField(
                        choices=[
                            ("zatca", "هيئة الزكاة والضريبة والجمارك - ZATCA"),
                            ("fta", "الهيئة الاتحادية للضرائب - FTA (UAE)"),
                            ("nbr", "الجهاز الوطني للإيرادات - NBR (Bahrain)"),
                            ("gta", "الهيئة العامة للضرائب - GTA (Qatar)"),
                            ("mof_kw", "وزارة المالية - MOF (Kuwait)"),
                            ("tra", "جهاز الضرائب - TRA (Oman)"),
                            ("ifrs", "المعايير الدولية للتقارير المالية - IFRS"),
                            ("gaap", "المبادئ المحاسبية المقبولة عموماً - GAAP"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("vat", "ضريبة القيمة المضافة - VAT"),
                            ("zakat", "الزكاة - Zakat"),
                            ("einvoice", "الفوترة الإلكترونية - E-Invoicing"),
                            ("transfer_pricing", "التسعير التحويلي - Transfer Pricing"),
                            ("aml", "مكافحة غسل الأموال - AML"),
                            ("corporate_tax", "ضريبة الشركات - Corporate Tax"),
                            ("withholding", "الضريبة المستقطعة - Withholding Tax"),
                        ],
                        max_length=30,
                    ),
                ),
                ("article_number", models.CharField(max_length=50)),
                (
                    "clause_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("title_ar", models.CharField(max_length=500)),
                ("title_en", models.CharField(blank=True, max_length=500, null=True)),
                ("description_ar", models.TextField()),
                ("description_en", models.TextField(blank=True, null=True)),
                ("penalty_description_ar", models.TextField(blank=True, null=True)),
                (
                    "penalty_amount_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "penalty_amount_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("last_updated", models.DateField(blank=True, null=True)),
                ("source_url", models.URLField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "regulatory_references",
                "ordering": ["regulator", "article_number"],
                "indexes": [
                    models.Index(
                        fields=["regulator"], name="regulatory__regulat_959eff_idx"
                    ),
                    models.Index(
                        fields=["category"], name="regulatory__categor_1a8360_idx"
                    ),
                ],
                "unique_together": {("regulator", "article_number", "clause_number")},
            },
        ),
        migrations.CreateModel(
            name="VATReconciliation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("monthly", "شهري - Monthly"),
                            ("quarterly", "ربع سنوي - Quarterly"),
                        ],
                        default="monthly",
                        max_length=10,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "output_vat_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "output_vat_adjustments",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_output_vat",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "input_vat_purchases",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "input_vat_imports",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "input_vat_adjustments",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_input_vat",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "net_vat_due",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "gl_vat_payable_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "gl_vat_receivable_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "output_vat_variance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "input_vat_variance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_variance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("variance_explanation_ar", models.TextField(blank=True, null=True)),
                ("variance_explanation_en", models.TextField(blank=True, null=True)),
                ("compliance_score", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة - Draft"),
                            ("in_progress", "قيد المراجعة - In Progress"),
                            ("completed", "مكتمل - Completed"),
                            ("submitted", "تم التقديم - Submitted"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vat_reconciliations",
                        to="core.organization",
                    ),
                ),
                (
                    "prepared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prepared_vat_reconciliations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_vat_reconciliations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "vat_reconciliations",
                "ordering": ["-period_start"],
            },
        ),
        migrations.CreateModel(
            name="ZakatCalculation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fiscal_year_start", models.DateField()),
                ("fiscal_year_end", models.DateField()),
                (
                    "total_equity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "long_term_liabilities",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "provisions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "adjusted_net_profit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "positive_zakat_base",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "fixed_assets",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "long_term_investments",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "accumulated_losses",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "net_zakat_base",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "zakat_rate",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.025"), max_digits=5
                    ),
                ),
                (
                    "zakat_due",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "income_tax_due",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "zakat_tax_difference",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("difference_explanation_ar", models.TextField(blank=True, null=True)),
                ("calculation_details", models.JSONField(blank=True, null=True)),
                ("adjustments_json", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة - Draft"),
                            ("calculated", "تم الحساب - Calculated"),
                            ("reviewed", "تمت المراجعة - Reviewed"),
                            ("submitted", "تم التقديم - Submitted"),
                            ("assessed", "تم التقييم - Assessed by ZATCA"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("compliance_score", models.IntegerField(default=0)),
                ("findings_ar", models.TextField(blank=True, null=True)),
                ("override_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zakat_calculations",
                        to="core.organization",
                    ),
                ),
                (
                    "override_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="override_zakat",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prepared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prepared_zakat",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_zakat",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "zakat_calculations",
                "ordering": ["-fiscal_year_end"],
            },
        ),
        migrations.CreateModel(
            name="ZakatDiscrepancy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "discrepancy_type",
                    models.CharField(
                        choices=[
                            (
                                "equity_classification",
                                "تصنيف حقوق الملكية - Equity Classification",
                            ),
                            ("asset_valuation", "تقييم الأصول - Asset Valuation"),
                            (
                                "provision_treatment",
                                "معالجة المخصصات - Provision Treatment",
                            ),
                            ("profit_adjustment", "تعديل الأرباح - Profit Adjustment"),
                            (
                                "deduction_eligibility",
                                "أهلية الحسومات - Deduction Eligibility",
                            ),
                            ("calculation_error", "خطأ حسابي - Calculation Error"),
                        ],
                        max_length=30,
                    ),
                ),
                ("field_name", models.CharField(max_length=100)),
                (
                    "reported_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "calculated_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("variance", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "impact_on_zakat",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("description_ar", models.TextField()),
                ("description_en", models.TextField(blank=True, null=True)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "منخفض - Low"),
                            ("medium", "متوسط - Medium"),
                            ("high", "مرتفع - High"),
                            ("critical", "حرج - Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolution_ar", models.TextField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "regulatory_reference",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="zakat_discrepancies",
                        to="compliance.regulatoryreference",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "zakat_calculation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discrepancies",
                        to="compliance.zakatcalculation",
                    ),
                ),
            ],
            options={
                "db_table": "zakat_discrepancies",
            },
        ),
        migrations.CreateModel(
            name="ZATCAInvoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("invoice_number", models.CharField(max_length=127)),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "invoice_type_code",
                    models.CharField(
                        choices=[
                            ("388", "فاتورة ضريبية - Tax Invoice"),
                            ("381", "إشعار دائن - Credit Note"),
                            ("383", "إشعار مدين - Debit Note"),
                        ],
                        default="388",
                        max_length=3,
                    ),
                ),
                (
                    "invoice_subtype",
                    models.CharField(
                        choices=[
                            ("0100000", "فاتورة ضريبية قياسية - Standard Tax Invoice"),
                            ("0200000", "فاتورة ضريبية مبسطة - Simplified Tax Invoice"),
                        ],
                        default="0100000",
                        max_length=7,
                    ),
                ),
                ("issue_date", models.DateField()),
                ("issue_time", models.TimeField()),
                ("supply_date", models.DateField(blank=True, null=True)),
                ("seller_name", models.CharField(max_length=255)),
                ("seller_vat_number", models.CharField(max_length=15)),
                ("seller_address", models.TextField()),
                ("seller_city", models.CharField(max_length=100)),
                (
                    "seller_postal_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("seller_country", models.CharField(default="SA", max_length=2)),
                ("buyer_name", models.CharField(max_length=255)),
                (
                    "buyer_vat_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("buyer_address", models.TextField(blank=True, null=True)),
                ("buyer_city", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "buyer_postal_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("buyer_country", models.CharField(default="SA", max_length=2)),
                (
                    "total_excluding_vat",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("total_vat", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "total_including_vat",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "total_discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("currency_code", models.CharField(default="SAR", max_length=3)),
                ("line_items_json", models.JSONField()),
                (
                    "previous_invoice_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "invoice_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("qr_code", models.TextField(blank=True, null=True)),
                ("xml_content", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة - Draft"),
                            ("validated", "تم التحقق - Validated"),
                            ("reported", "تم الإبلاغ - Reported to ZATCA"),
                            ("cleared", "تمت الموافقة - Cleared"),
                            ("rejected", "مرفوضة - Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("validation_errors", models.JSONField(blank=True, null=True)),
                ("zatca_response", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zatca_invoices",
                        to="core.organization",
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="zatca_invoices",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "db_table": "zatca_invoices",
                "ordering": ["-issue_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VATDiscrepancy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "discrepancy_type",
                    models.CharField(
                        choices=[
                            ("timing", "توقيت - Timing Difference"),
                            ("calculation", "حساب - Calculation Error"),
                            ("missing_invoice", "فاتورة مفقودة - Missing Invoice"),
                            ("duplicate", "مكرر - Duplicate"),
                            ("rate_error", "خطأ في النسبة - Rate Error"),
                            ("exemption", "إعفاء - Exemption Issue"),
                            ("classification", "تصنيف - Classification Error"),
                        ],
                        max_length=30,
                    ),
                ),
                ("expected_vat", models.DecimalField(decimal_places=2, max_digits=15)),
                ("actual_vat", models.DecimalField(decimal_places=2, max_digits=15)),
                ("variance", models.DecimalField(decimal_places=2, max_digits=15)),
                ("description_ar", models.TextField()),
                ("description_en", models.TextField(blank=True, null=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolution_ar", models.TextField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "regulatory_reference",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vat_discrepancies",
                        to="compliance.regulatoryreference",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vat_discrepancies",
                        to="documents.transaction",
                    ),
                ),
                (
                    "reconciliation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discrepancies",
                        to="compliance.vatreconciliation",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discrepancies",
                        to="compliance.zatcainvoice",
                    ),
                ),
            ],
            options={
                "db_table": "vat_discrepancies",
            },
        ),
        migrations.CreateModel(
            name="ZATCAValidationResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "check_type",
                    models.CharField(
                        choices=[
                            ("mandatory_field", "حقل إلزامي - Mandatory Field"),
                            ("format", "تنسيق - Format"),
                            ("calculation", "حساب - Calculation"),
                            ("business_rule", "قاعدة عمل - Business Rule"),
                            ("xml_schema", "مخطط XML - XML Schema"),
                            ("signature", "توقيع - Signature"),
                            ("hash", "تجزئة - Hash"),
                        ],
                        max_length=30,
                    ),
                ),
                ("field_name", models.CharField(max_length=100)),
                ("is_valid", models.BooleanField(default=False)),
                ("error_code", models.CharField(blank=True, max_length=50, null=True)),
                ("message_ar", models.TextField()),
                ("message_en", models.TextField(blank=True, null=True)),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_results",
                        to="compliance.zatcainvoice",
                    ),
                ),
                (
                    "regulatory_reference",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validation_results",
                        to="compliance.regulatoryreference",
                    ),
                ),
            ],
            options={
                "db_table": "zatca_validation_results",
            },
        ),
        migrations.CreateModel(
            name="AuditFinding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("finding_number", models.CharField(max_length=50)),
                (
                    "finding_type",
                    models.CharField(
                        choices=[
                            ("compliance", "امتثال - Compliance"),
                            ("accuracy", "دقة - Accuracy"),
                            ("completeness", "اكتمال - Completeness"),
                            ("timeliness", "التوقيت - Timeliness"),
                            ("documentation", "توثيق - Documentation"),
                            ("internal_control", "رقابة داخلية - Internal Control"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "منخفض - Low"),
                            ("medium", "متوسط - Medium"),
                            ("high", "مرتفع - High"),
                            ("critical", "حرج - Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                ("title_ar", models.CharField(max_length=500)),
                ("title_en", models.CharField(blank=True, max_length=500, null=True)),
                ("description_ar", models.TextField()),
                ("description_en", models.TextField(blank=True, null=True)),
                ("impact_ar", models.TextField()),
                ("impact_en", models.TextField(blank=True, null=True)),
                (
                    "financial_impact",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("recommendation_ar", models.TextField()),
                ("recommendation_en", models.TextField(blank=True, null=True)),
                (
                    "related_entity_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("related_entity_id", models.UUIDField(blank=True, null=True)),
                ("ai_explanation_ar", models.TextField(blank=True, null=True)),
                ("ai_confidence", models.IntegerField(default=0)),
                ("is_resolved", models.BooleanField(default=False)),
                ("management_response_ar", models.TextField(blank=True, null=True)),
                ("action_plan_ar", models.TextField(blank=True, null=True)),
                ("target_resolution_date", models.DateField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identified_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identified_findings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_findings",
                        to="core.organization",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_findings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "regulatory_reference",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_findings",
                        to="compliance.regulatoryreference",
                    ),
                ),
            ],
            options={
                "db_table": "audit_findings",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization"], name="audit_findi_organiz_ff1768_idx"
                    ),
                    models.Index(
                        fields=["finding_type"], name="audit_findi_finding_f310c0_idx"
                    ),
                    models.Index(
                        fields=["risk_level"], name="audit_findi_risk_le_674c68_idx"
                    ),
                    models.Index(
                        fields=["is_resolved"], name="audit_findi_is_reso_b7451f_idx"
                    ),
                ],
                "unique_together": {("organization", "finding_number")},
            },
        ),
        migrations.AddIndex(
            model_name="vatreconciliation",
            index=models.Index(
                fields=["organization"], name="vat_reconci_organiz_540a46_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vatreconciliation",
            index=models.Index(
                fields=["period_start"], name="vat_reconci_period__c26df6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vatreconciliation",
            index=models.Index(fields=["status"], name="vat_reconci_status_b4005e_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="vatreconciliation",
            unique_together={("organization", "period_start", "period_end")},
        ),
        migrations.AddIndex(
            model_name="zakatcalculation",
            index=models.Index(
                fields=["organization"], name="zakat_calcu_organiz_de29d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="zakatcalculation",
            index=models.Index(
                fields=["fiscal_year_end"], name="zakat_calcu_fiscal__4f51fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="zakatcalculation",
            index=models.Index(fields=["status"], name="zakat_calcu_status_a9e1e3_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="zakatcalculation",
            unique_together={("organization", "fiscal_year_start", "fiscal_year_end")},
        ),
        migrations.AddIndex(
            model_name="zakatdiscrepancy",
            index=models.Index(
                fields=["zakat_calculation"], name="zakat_discr_zakat_c_03e688_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="zakatdiscrepancy",
            index=models.Index(
                fields=["discrepancy_type"], name="zakat_discr_discrep_1588a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="zakatdiscrepancy",
            index=models.Index(
                fields=["risk_level"], name="zakat_discr_risk_le_f15048_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="zakatdiscrepancy",
            index=models.Index(
                fields=["is_resolved"], name="zakat_discr_is_reso_9aa68b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="zatcainvoice",
            index=models.Index(
                fields=["organization"], name="zatca_invoi_organiz_061c51_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="zatcainvoice",
            index=models.Index(fields=["status"], name="zatca_invoi_status_896180_idx"),
        ),
        migrations.AddIndex(
            model_name="zatcainvoice",
            index=models.Index(
                fields=["issue_date"], name="zatca_invoi_issue_d_350583_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="zatcainvoice",
            index=models.Index(
                fields=["seller_vat_number"], name="zatca_invoi_seller__ad245e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="zatcainvoice",
            unique_together={("organization", "invoice_number")},
        ),
        migrations.AddIndex(
            model_name="vatdiscrepancy",
            index=models.Index(
                fields=["reconciliation"], name="vat_discrep_reconci_ef5ec9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vatdiscrepancy",
            index=models.Index(
                fields=["discrepancy_type"], name="vat_discrep_discrep_436601_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vatdiscrepancy",
            index=models.Index(
                fields=["is_resolved"], name="vat_discrep_is_reso_b08255_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="zatcavalidationresult",
            index=models.Index(
                fields=["invoice"], name="zatca_valid_invoice_4131a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="zatcavalidationresult",
            index=models.Index(
                fields=["is_valid"], name="zatca_valid_is_vali_9218dd_idx"
            ),
        ),
    ]
