# Generated by Django 5.0.1 on 2026-01-27 13:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0001_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ZATCALiveVerificationReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("verification_timestamp", models.DateTimeField()),
                (
                    "verification_type",
                    models.CharField(
                        default="post_transaction",
                        help_text="READ-ONLY verification type",
                        max_length=50,
                    ),
                ),
                (
                    "overall_status",
                    models.CharField(
                        choices=[
                            ("passed", "ناجح - Passed"),
                            ("warning", "تحذير - Warning"),
                            ("failed", "فشل - Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("compliance_score", models.IntegerField(default=0)),
                ("total_checks", models.IntegerField(default=0)),
                ("passed_checks", models.IntegerField(default=0)),
                ("failed_checks", models.IntegerField(default=0)),
                ("warning_checks", models.IntegerField(default=0)),
                (
                    "verification_results_json",
                    models.JSONField(help_text="Detailed verification results"),
                ),
                (
                    "hash_verification_json",
                    models.JSONField(
                        blank=True,
                        help_text="Hash chain verification details",
                        null=True,
                    ),
                ),
                ("summary_ar", models.TextField(help_text="Arabic summary")),
                (
                    "summary_en",
                    models.TextField(
                        blank=True, help_text="English summary", null=True
                    ),
                ),
                (
                    "critical_errors_json",
                    models.JSONField(
                        blank=True,
                        help_text="Critical errors that block compliance",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scope_declaration",
                    models.TextField(
                        default="READ-ONLY POST-TRANSACTION VERIFICATION",
                        help_text="Documents that this is read-only verification, not invoice submission",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_verification_reports",
                        to="compliance.zatcainvoice",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zatca_verification_reports",
                        to="core.organization",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zatca_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "zatca_live_verification_reports",
                "ordering": ["-verification_timestamp"],
                "indexes": [
                    models.Index(
                        fields=["invoice"], name="zatca_live__invoice_295edf_idx"
                    ),
                    models.Index(
                        fields=["organization"], name="zatca_live__organiz_8ad8ac_idx"
                    ),
                    models.Index(
                        fields=["overall_status"], name="zatca_live__overall_fa6c97_idx"
                    ),
                    models.Index(
                        fields=["verification_timestamp"],
                        name="zatca_live__verific_126462_idx",
                    ),
                ],
            },
        ),
    ]
