# Generated by Django 5.0.1 on 2026-01-27 20:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0002_zatca_live_verification"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIExplanationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "explanation_ar",
                    models.TextField(help_text="Generated Arabic explanation"),
                ),
                ("confidence_score", models.IntegerField(default=0)),
                ("confidence_level", models.CharField(default="medium", max_length=20)),
                ("model_used", models.CharField(max_length=100)),
                ("provider", models.CharField(max_length=50)),
                ("session_id", models.CharField(max_length=100)),
                ("processing_time_ms", models.IntegerField(default=0)),
                (
                    "audit_hash",
                    models.CharField(
                        help_text="SHA-256 hash for integrity", max_length=64
                    ),
                ),
                ("is_advisory", models.BooleanField(default=True)),
                ("requires_human_review", models.BooleanField(default=True)),
                ("human_reviewed", models.BooleanField(default=False)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True, null=True)),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد المراجعة - Pending Review"),
                            ("approved", "معتمد - Approved"),
                            ("modified", "معدل - Modified"),
                            ("rejected", "مرفوض - Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scope_declaration",
                    models.TextField(
                        default="ADVISORY ONLY - REQUIRES HUMAN REVIEW",
                        help_text="Documents that this is advisory output requiring human review",
                    ),
                ),
                (
                    "finding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_explanation_logs",
                        to="compliance.auditfinding",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_ai_explanations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_explanation_logs",
                        to="core.organization",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_ai_explanations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_explanation_logs",
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["finding"], name="ai_explanat_finding_bfd15e_idx"
                    ),
                    models.Index(
                        fields=["organization"], name="ai_explanat_organiz_e89dbd_idx"
                    ),
                    models.Index(
                        fields=["approval_status"],
                        name="ai_explanat_approva_887ec1_idx",
                    ),
                    models.Index(
                        fields=["generated_at"], name="ai_explanat_generat_453d5d_idx"
                    ),
                ],
            },
        ),
    ]
