# Generated by Django 5.0.1 on 2026-01-27 22:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0003_add_ai_explanation_log"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ZATCAVerificationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("verification_type", models.CharField(max_length=50)),
                ("input_identifier", models.CharField(max_length=255)),
                ("is_valid", models.BooleanField(default=False)),
                ("compliance_score", models.IntegerField(default=0)),
                ("passed_checks", models.IntegerField(default=0)),
                ("failed_checks", models.IntegerField(default=0)),
                ("message_ar", models.TextField(blank=True, null=True)),
                ("message_en", models.TextField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=50, null=True)),
                ("response_json", models.JSONField()),
                ("processing_time_ms", models.IntegerField(default=0)),
                ("audit_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scope_declaration",
                    models.TextField(
                        default="VERIFICATION ONLY - No submission, clearance, or signing",
                        help_text="Documents the read-only nature of this verification",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zatca_verification_logs",
                        to="core.organization",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zatca_api_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "zatca_verification_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization"], name="zatca_verif_organiz_3ef361_idx"
                    ),
                    models.Index(
                        fields=["verification_type"],
                        name="zatca_verif_verific_711304_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="zatca_verif_created_557f8e_idx"
                    ),
                ],
            },
        ),
    ]
