# Generated by Django 5.0.1 on 2026-01-26 17:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Insight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("anomaly", "Anomaly"),
                            ("prediction", "Prediction"),
                            ("trend", "Trend"),
                            ("recommendation", "Recommendation"),
                            ("alert", "Alert"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "related_entity_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("related_entity_id", models.UUIDField(blank=True, null=True)),
                ("data_json", models.JSONField(blank=True, null=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insights",
                        to="core.organization",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_insights",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "insights",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization"], name="insights_organiz_26237b_idx"
                    ),
                    models.Index(
                        fields=["insight_type"], name="insights_insight_89a2d0_idx"
                    ),
                    models.Index(
                        fields=["severity"], name="insights_severit_bc2a43_idx"
                    ),
                    models.Index(
                        fields=["is_resolved"], name="insights_is_reso_b8ac84_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("income_statement", "Income Statement"),
                            ("balance_sheet", "Balance Sheet"),
                            ("cash_flow", "Cash Flow"),
                            ("vat_return", "VAT Return"),
                            ("audit_report", "Audit Report"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                ("report_name", models.CharField(max_length=255)),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("generated", "Generated"),
                            ("reviewed", "Reviewed"),
                            ("approved", "Approved"),
                            ("submitted", "Submitted"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("data_json", models.JSONField(blank=True, null=True)),
                (
                    "storage_key",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("storage_url", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="core.organization",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reports",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization"], name="reports_organiz_8b24a8_idx"
                    ),
                    models.Index(
                        fields=["report_type"], name="reports_report__ff8b25_idx"
                    ),
                    models.Index(fields=["status"], name="reports_status_e83c1d_idx"),
                ],
            },
        ),
    ]
