# Generated by Django 5.0.1 on 2026-01-29 23:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_organization_logo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HardRulesEvaluation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "evaluation_type",
                    models.CharField(
                        choices=[
                            ("invoice", "فاتورة - Invoice"),
                            ("journal_entry", "قيد يومية - Journal Entry"),
                            ("transaction", "معاملة - Transaction"),
                            ("document", "مستند - Document"),
                            ("full_flow", "تدفق كامل - Full Flow"),
                        ],
                        max_length=20,
                    ),
                ),
                ("entity_type", models.CharField(blank=True, max_length=50, null=True)),
                ("entity_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "overall_status",
                    models.CharField(
                        choices=[
                            ("PASS", "ناجح - Pass"),
                            ("FAIL", "فشل - Fail"),
                            ("BLOCKED", "محظور - Blocked"),
                            ("WARNING", "تحذير - Warning"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_eligible_for_ai", models.BooleanField(default=False)),
                ("total_rules_checked", models.IntegerField(default=0)),
                ("passed_count", models.IntegerField(default=0)),
                ("failed_count", models.IntegerField(default=0)),
                ("blocked_count", models.IntegerField(default=0)),
                ("warning_count", models.IntegerField(default=0)),
                ("results_json", models.JSONField(blank=True, null=True)),
                ("critical_failures_json", models.JSONField(blank=True, null=True)),
                ("blocking_issues_json", models.JSONField(blank=True, null=True)),
                ("blocking_message", models.TextField(blank=True, null=True)),
                ("blocking_message_ar", models.TextField(blank=True, null=True)),
                ("report_hash", models.CharField(max_length=64)),
                (
                    "evaluated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hard_rules_evaluations",
                        to="core.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hard_rules_evaluations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hard_rules_evaluations",
                "ordering": ["-evaluated_at"],
            },
        ),
        migrations.CreateModel(
            name="AIExecutionGateLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("ALLOWED", "مسموح - Allowed"),
                            ("BLOCKED", "محظور - Blocked"),
                        ],
                        max_length=10,
                    ),
                ),
                ("ai_function_name", models.CharField(max_length=100)),
                ("blocking_reason", models.TextField(blank=True, null=True)),
                ("blocking_reason_ar", models.TextField(blank=True, null=True)),
                (
                    "gate_checked_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_gate_logs",
                        to="core.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_gate_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "evaluation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gate_logs",
                        to="hard_rules.hardrulesevaluation",
                    ),
                ),
            ],
            options={
                "db_table": "ai_execution_gate_logs",
                "ordering": ["-gate_checked_at"],
            },
        ),
        migrations.CreateModel(
            name="HardRulesRuleResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rule_id", models.CharField(max_length=20)),
                ("rule_name", models.CharField(max_length=100)),
                ("rule_name_ar", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("accounting", "محاسبة - Accounting"),
                            ("invoice", "فاتورة - Invoice"),
                            ("vat", "ض.ق.م - VAT"),
                            ("compliance", "امتثال - Compliance"),
                            ("ocr", "تعرف ضوئي - OCR"),
                            ("security", "أمان - Security"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PASS", "ناجح - Pass"),
                            ("FAIL", "فشل - Fail"),
                            ("BLOCKED", "محظور - Blocked"),
                            ("WARNING", "تحذير - Warning"),
                        ],
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                ("message_ar", models.TextField()),
                ("details_json", models.JSONField(blank=True, null=True)),
                (
                    "evaluation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule_results",
                        to="hard_rules.hardrulesevaluation",
                    ),
                ),
            ],
            options={
                "db_table": "hard_rules_rule_results",
            },
        ),
        migrations.AddIndex(
            model_name="hardrulesevaluation",
            index=models.Index(
                fields=["organization"], name="hard_rules__organiz_4d9406_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hardrulesevaluation",
            index=models.Index(
                fields=["overall_status"], name="hard_rules__overall_b75fce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hardrulesevaluation",
            index=models.Index(
                fields=["evaluation_type"], name="hard_rules__evaluat_97d0d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hardrulesevaluation",
            index=models.Index(
                fields=["evaluated_at"], name="hard_rules__evaluat_b64368_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hardrulesevaluation",
            index=models.Index(
                fields=["entity_id"], name="hard_rules__entity__aba0ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiexecutiongatelog",
            index=models.Index(
                fields=["organization"], name="ai_executio_organiz_3401fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiexecutiongatelog",
            index=models.Index(
                fields=["decision"], name="ai_executio_decisio_e8559c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiexecutiongatelog",
            index=models.Index(
                fields=["gate_checked_at"], name="ai_executio_gate_ch_8714aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hardrulesruleresult",
            index=models.Index(
                fields=["evaluation"], name="hard_rules__evaluat_a67ea6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hardrulesruleresult",
            index=models.Index(
                fields=["rule_id"], name="hard_rules__rule_id_3a1cc1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hardrulesruleresult",
            index=models.Index(fields=["status"], name="hard_rules__status_fcbdc8_idx"),
        ),
        migrations.AddIndex(
            model_name="hardrulesruleresult",
            index=models.Index(
                fields=["category"], name="hard_rules__categor_404999_idx"
            ),
        ),
    ]
