# Generated by Django 5.0.1 on 2026-01-30 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIPluginSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plugin_code", models.CharField(max_length=100, unique=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("google", "Google AI"),
                            ("openai", "OpenAI"),
                            ("local", "Local / Mock"),
                        ],
                        default="local",
                        max_length=50,
                    ),
                ),
                ("model_name", models.CharField(blank=True, max_length=100)),
                ("temperature", models.FloatField(default=0.0)),
                ("max_tokens", models.IntegerField(default=2048)),
                ("prompt_text", models.TextField(blank=True)),
                ("is_enabled", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
