# Generated by Django 5.0.1 on 2026-01-30 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_plugins", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aipluginsetting",
            name="provider",
            field=models.CharField(
                choices=[
                    ("google", "Google AI"),
                    ("openai", "OpenAI"),
                    ("local", "Local / Mock"),
                ],
                default="openai",
                max_length=50,
            ),
        ),
    ]
