# Generated by Django 5.0.1 on 2026-03-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_plugins", "0002_alter_aipluginsetting_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aipluginsetting",
            name="provider",
            field=models.CharField(
                choices=[
                    ("openai", "OpenAI"),
                    ("google_cloud", "Google Cloud AI"),
                    ("azure", "Azure Cognitive Services"),
                    ("local", "Local Model"),
                    ("scikit-learn", "Pattern Engine"),
                    ("Gensim", "Text Normalizer"),
                    ("PyOD", "Risk Signal"),
                    ("Tesseract", "Document Reader"),
                    ("Rules Engine", "Compliance Validator"),
                ],
                default="Gensim",
                max_length=50,
            ),
        ),
    ]
