# Generated by Django 5.0.1 on 2026-01-27 09:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditFlag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "flag_type",
                    models.CharField(
                        choices=[
                            ("duplicate", "Potential Duplicate"),
                            ("unusual_amount", "Unusual Amount"),
                            ("unusual_timing", "Unusual Timing"),
                            ("missing_approval", "Missing Approval"),
                            ("vat_error", "VAT Calculation Error"),
                            ("compliance_violation", "Compliance Violation"),
                            ("fraud_risk", "Potential Fraud"),
                            ("data_quality", "Data Quality Issue"),
                            ("manual_review", "Requires Manual Review"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("details_json", models.JSONField(blank=True, null=True)),
                ("is_ai_detected", models.BooleanField(default=True)),
                ("confidence_score", models.IntegerField(default=0)),
                ("is_resolved", models.BooleanField(default=False)),
                (
                    "resolution_action",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "audit_flags",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ComplianceCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "check_type",
                    models.CharField(
                        choices=[
                            ("vat", "VAT Compliance"),
                            ("zatca", "ZATCA Compliance"),
                            ("shariah", "Shariah Compliance"),
                            ("ifrs", "IFRS Compliance"),
                            ("aml", "Anti-Money Laundering"),
                            ("general", "General Compliance"),
                        ],
                        max_length=20,
                    ),
                ),
                ("check_name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("warning", "Warning"),
                            ("exempted", "Exempted"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("compliance_score", models.IntegerField(default=0)),
                (
                    "related_entity_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("related_entity_id", models.UUIDField(blank=True, null=True)),
                ("violation_details", models.JSONField(blank=True, null=True)),
                ("recommendation", models.TextField(blank=True, null=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True, null=True)),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "compliance_checks",
                "ordering": ["-checked_at"],
            },
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("entry_number", models.CharField(max_length=50)),
                ("entry_date", models.DateTimeField()),
                ("description", models.TextField()),
                ("reference", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("posted", "Posted"),
                            ("reversed", "Reversed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "total_debit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_credit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("is_balanced", models.BooleanField(default=False)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "journal_entries",
                "ordering": ["-entry_date"],
            },
        ),
        migrations.CreateModel(
            name="JournalEntryLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "debit_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "credit_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
            ],
            options={
                "db_table": "journal_entry_lines",
            },
        ),
        migrations.AddField(
            model_name="transaction",
            name="anomaly_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="is_anomaly",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="reference_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="vat_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("account_code", models.CharField(max_length=20)),
                ("account_name", models.CharField(max_length=255)),
                (
                    "account_name_ar",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("asset", "Asset"),
                            ("liability", "Liability"),
                            ("equity", "Equity"),
                            ("revenue", "Revenue"),
                            ("expense", "Expense"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "account_subtype",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cash", "Cash & Cash Equivalents"),
                            ("accounts_receivable", "Accounts Receivable"),
                            ("inventory", "Inventory"),
                            ("prepaid", "Prepaid Expenses"),
                            ("fixed_assets", "Fixed Assets"),
                            ("accounts_payable", "Accounts Payable"),
                            ("vat_payable", "VAT Payable"),
                            ("loans", "Loans & Borrowings"),
                            ("accrued", "Accrued Liabilities"),
                            ("capital", "Capital"),
                            ("retained_earnings", "Retained Earnings"),
                            ("sales", "Sales Revenue"),
                            ("service_income", "Service Income"),
                            ("other_income", "Other Income"),
                            ("cost_of_goods", "Cost of Goods Sold"),
                            ("salaries", "Salaries & Wages"),
                            ("rent", "Rent Expense"),
                            ("utilities", "Utilities"),
                            ("marketing", "Marketing & Advertising"),
                            ("other_expense", "Other Expenses"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "opening_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("currency", models.CharField(default="SAR", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="core.organization",
                    ),
                ),
                (
                    "parent_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sub_accounts",
                        to="documents.account",
                    ),
                ),
            ],
            options={
                "db_table": "accounts",
                "ordering": ["account_code"],
            },
        ),
        migrations.AddField(
            model_name="transaction",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="documents.account",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["is_anomaly"], name="transaction_is_anom_a6568d_idx"
            ),
        ),
        migrations.AddField(
            model_name="auditflag",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_flags",
                to="documents.document",
            ),
        ),
        migrations.AddField(
            model_name="auditflag",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_flags",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="auditflag",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_flags",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="auditflag",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_flags",
                to="documents.transaction",
            ),
        ),
        migrations.AddField(
            model_name="compliancecheck",
            name="checked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="compliance_checks_performed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="compliancecheck",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compliance_checks",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="compliancecheck",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_compliance",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journal_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="journal_entries",
                to="documents.document",
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journal_entries",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="posted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posted_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="journalentryline",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="journal_lines",
                to="documents.account",
            ),
        ),
        migrations.AddField(
            model_name="journalentryline",
            name="journal_entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="documents.journalentry",
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["organization"], name="accounts_organiz_2ac657_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["account_type"], name="accounts_account_8fba74_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["account_code"], name="accounts_account_e87462_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="account",
            unique_together={("organization", "account_code")},
        ),
        migrations.AddIndex(
            model_name="auditflag",
            index=models.Index(
                fields=["organization"], name="audit_flags_organiz_ef7c87_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditflag",
            index=models.Index(
                fields=["flag_type"], name="audit_flags_flag_ty_4c8c2b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditflag",
            index=models.Index(
                fields=["priority"], name="audit_flags_priorit_6020fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditflag",
            index=models.Index(
                fields=["is_resolved"], name="audit_flags_is_reso_6a9cf4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="compliancecheck",
            index=models.Index(
                fields=["organization"], name="compliance__organiz_8b8485_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="compliancecheck",
            index=models.Index(
                fields=["check_type"], name="compliance__check_t_1e7fd5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="compliancecheck",
            index=models.Index(fields=["status"], name="compliance__status_2a0297_idx"),
        ),
        migrations.AddIndex(
            model_name="compliancecheck",
            index=models.Index(
                fields=["severity"], name="compliance__severit_408ad6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="compliancecheck",
            index=models.Index(
                fields=["is_resolved"], name="compliance__is_reso_7ebfb6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["organization"], name="journal_ent_organiz_505228_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["entry_date"], name="journal_ent_entry_d_8a53f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(fields=["status"], name="journal_ent_status_f21256_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="journalentry",
            unique_together={("organization", "entry_number")},
        ),
        migrations.AddIndex(
            model_name="journalentryline",
            index=models.Index(
                fields=["journal_entry"], name="journal_ent_journal_d48be9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentryline",
            index=models.Index(
                fields=["account"], name="journal_ent_account_d36604_idx"
            ),
        ),
    ]
