# Generated by Django 5.0.1 on 2026-01-27 18:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("documents", "0002_auditflag_compliancecheck_journalentry_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OCREvidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "raw_text",
                    models.TextField(help_text="Full extracted text - IMMUTABLE"),
                ),
                (
                    "text_ar",
                    models.TextField(
                        blank=True, help_text="Arabic text portions", null=True
                    ),
                ),
                (
                    "text_en",
                    models.TextField(
                        blank=True, help_text="English text portions", null=True
                    ),
                ),
                (
                    "confidence_score",
                    models.IntegerField(default=0, help_text="OCR confidence 0-100"),
                ),
                (
                    "confidence_level",
                    models.CharField(
                        choices=[
                            ("high", "مرتفعة - High"),
                            ("medium", "متوسطة - Medium"),
                            ("low", "منخفضة - Low"),
                            ("very_low", "ضعيفة جداً - Very Low"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                ("page_count", models.IntegerField(default=1)),
                ("word_count", models.IntegerField(default=0)),
                ("ocr_engine", models.CharField(default="tesseract", max_length=50)),
                ("ocr_version", models.CharField(blank=True, max_length=50, null=True)),
                ("language_used", models.CharField(default="mixed", max_length=20)),
                ("is_handwritten", models.BooleanField(default=False)),
                ("processing_time_ms", models.IntegerField(default=0)),
                (
                    "extracted_invoice_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "extracted_vat_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "extracted_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "extracted_tax",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("structured_data_json", models.JSONField(blank=True, null=True)),
                (
                    "evidence_hash",
                    models.CharField(
                        help_text="SHA-256 hash for evidence integrity", max_length=64
                    ),
                ),
                ("extracted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scope_declaration",
                    models.TextField(
                        default="OCR EVIDENCE - READ-ONLY, NOT SOURCE OF TRUTH",
                        help_text="Documents that this is audit evidence only",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocr_evidence_records",
                        to="documents.document",
                    ),
                ),
                (
                    "extracted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocr_extractions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocr_evidence",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "ocr_evidence",
                "ordering": ["-extracted_at"],
                "indexes": [
                    models.Index(
                        fields=["document"], name="ocr_evidenc_documen_b61bfd_idx"
                    ),
                    models.Index(
                        fields=["organization"], name="ocr_evidenc_organiz_3dbe9c_idx"
                    ),
                    models.Index(
                        fields=["confidence_level"],
                        name="ocr_evidenc_confide_4c0493_idx",
                    ),
                    models.Index(
                        fields=["extracted_at"], name="ocr_evidenc_extract_2877f5_idx"
                    ),
                ],
            },
        ),
    ]
