# Generated by Django 5.0.1 on 2026-03-06 13:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_organization_logo'),
        ('documents', '0003_ocr_evidence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='extracteddata',
            name='audit_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='audit_summary',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='compliance_checks',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='extraction_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='extraction_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='extraction_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='normalized_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='risk_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='risk_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='validation_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='validation_errors',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='validation_warnings',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('upload', 'Document Upload'), ('extraction', 'Invoice Extraction'), ('normalization', 'Data Normalization'), ('validation', 'Validation'), ('compliance_check', 'Compliance Check'), ('risk_score', 'Risk Scoring'), ('audit_summary', 'Audit Summary Generated'), ('review', 'User Review'), ('accept', 'Invoice Accepted'), ('reject', 'Invoice Rejected'), ('correct', 'Invoice Corrected'), ('finding_created', 'Audit Finding Created'), ('finding_resolved', 'Audit Finding Resolved')], max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_time', models.DateTimeField(auto_now_add=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('result_summary', models.TextField(blank=True, null=True)),
                ('phase', models.CharField(blank=True, max_length=20, null=True)),
                ('extracted_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trails', to='documents.extracteddata')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trails', to='core.organization')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_trail_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_trails',
                'ordering': ['-event_time'],
                'indexes': [models.Index(fields=['extracted_data'], name='audit_trail_extract_e4cf76_idx'), models.Index(fields=['organization'], name='audit_trail_organiz_84d9aa_idx'), models.Index(fields=['event_type'], name='audit_trail_event_t_d10a9e_idx'), models.Index(fields=['severity'], name='audit_trail_severit_7686e6_idx'), models.Index(fields=['event_time'], name='audit_trail_event_t_d5ca37_idx'), models.Index(fields=['success'], name='audit_trail_success_9c2bbd_idx')],
            },
        ),
        migrations.CreateModel(
            name='InvoiceAuditFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('finding_type', models.CharField(choices=[('total_mismatch', 'Total Mismatch'), ('vat_flag', 'VAT Flag'), ('line_total_mismatch', 'Line Total Mismatch'), ('missing_field', 'Missing Field'), ('invalid_value', 'Invalid Value'), ('date_mismatch', 'Date Mismatch'), ('other', 'Other')], max_length=30)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], default='medium', max_length=20)),
                ('description', models.TextField()),
                ('field', models.CharField(blank=True, max_length=100, null=True)),
                ('expected_value', models.TextField(blank=True, null=True)),
                ('actual_value', models.TextField(blank=True, null=True)),
                ('difference', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extracted_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_findings', to='documents.extracteddata')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_audit_findings', to='core.organization')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_invoice_findings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invoice_audit_findings',
                'ordering': ['-severity', '-created_at'],
                'indexes': [models.Index(fields=['extracted_data'], name='invoice_aud_extract_a5be11_idx'), models.Index(fields=['organization'], name='invoice_aud_organiz_c49451_idx'), models.Index(fields=['finding_type'], name='invoice_aud_finding_d9eaba_idx'), models.Index(fields=['severity'], name='invoice_aud_severit_b9d361_idx'), models.Index(fields=['is_resolved'], name='invoice_aud_is_reso_e3525e_idx')],
            },
        ),
    ]
