# Generated by Django 5.0.1 on 2026-03-06 17:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_organization_logo"),
        ("documents", "0004_extracteddata_audit_completed_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnomalyLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "anomaly_type",
                    models.CharField(
                        choices=[
                            ("amount_spike", "Amount Spike"),
                            ("amount_drop", "Amount Drop"),
                            ("discount_unusual", "Unusual Discount"),
                            ("frequency_spike", "Frequency Spike"),
                            ("frequency_drop", "Frequency Drop"),
                            ("pattern_break", "Pattern Break"),
                            ("tax_inconsistency", "Tax Inconsistency"),
                            ("date_anomaly", "Date Anomaly"),
                            ("duplicate_similarity", "Duplicate Similarity"),
                            ("vendor_new", "New Vendor"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                ("detected_value", models.TextField(blank=True, null=True)),
                ("expected_range", models.JSONField(blank=True, null=True)),
                (
                    "deviation_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("confidence_score", models.IntegerField(default=0)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="warning",
                        max_length=20,
                    ),
                ),
                ("context_data", models.JSONField(blank=True, null=True)),
                (
                    "detection_method",
                    models.CharField(
                        choices=[
                            ("statistical", "Statistical Analysis"),
                            ("pattern_matching", "Pattern Matching"),
                            ("rule_based", "Rule-Based"),
                            ("ml_model", "ML Model"),
                        ],
                        default="statistical",
                        max_length=50,
                    ),
                ),
                ("is_confirmed", models.BooleanField(default=False)),
                ("is_resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "anomaly_logs",
                "ordering": ["-severity", "-confidence_score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CashFlowForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_date", models.DateField()),
                ("due_date", models.DateField()),
                (
                    "invoice_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("currency", models.CharField(default="SAR", max_length=3)),
                ("projected_payment_30d", models.DateField(blank=True, null=True)),
                ("projected_payment_60d", models.DateField(blank=True, null=True)),
                ("projected_payment_90d", models.DateField(blank=True, null=True)),
                ("actual_payment_date", models.DateField(blank=True, null=True)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("scheduled", "Scheduled"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("confidence_score", models.FloatField(default=0.8)),
                (
                    "forecast_method",
                    models.CharField(
                        choices=[
                            ("historical_avg", "Historical Average"),
                            ("vendor_profile", "Vendor Profile"),
                            ("industry_standard", "Industry Standard"),
                            ("manual", "Manual Entry"),
                        ],
                        default="historical_avg",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "cash_flow_forecasts",
                "ordering": ["projected_payment_30d"],
            },
        ),
        migrations.CreateModel(
            name="CrossDocumentFinding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "finding_type",
                    models.CharField(
                        choices=[
                            ("potential_duplicate", "Potential Duplicate Invoice"),
                            ("unusual_amount", "Unusual Supplier Amount"),
                            ("vat_inconsistency", "VAT Inconsistency"),
                            ("suspicious_discount", "Suspicious Repeated Discount"),
                            ("frequency_anomaly", "Invoice Frequency Anomaly"),
                            ("amount_spike", "Unusual Amount Spike"),
                            ("vendor_pattern_break", "Breaks Vendor Pattern"),
                            ("cross_vendor_match", "Matches Another Vendor Invoice"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("analysis_details", models.JSONField(blank=True, null=True)),
                ("confidence_score", models.IntegerField(default=0)),
                (
                    "anomaly_score",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("is_resolved", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("under_review", "Under Review"),
                            ("dismissed", "Dismissed"),
                            ("confirmed", "Confirmed"),
                            ("duplicate_confirmed", "Duplicate Confirmed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "cross_document_findings",
                "ordering": ["-severity", "-confidence_score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FinancialAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("spend_spike", "Spend Spike Detected"),
                            ("duplicate_risk", "Duplicate Invoice Risk"),
                            ("anomaly_cluster", "Anomaly Cluster Detected"),
                            ("cash_flow_pressure", "Cash Flow Pressure"),
                            ("budget_overrun", "Budget Overrun Risk"),
                            ("vendor_risk_increase", "Vendor Risk Increase"),
                            ("payment_overdue", "Payment Overdue"),
                            ("category_variance", "Category Variance"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("trigger_details", models.JSONField(default=dict)),
                (
                    "affected_vendor",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "affected_category",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "affected_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("is_acknowledged", models.BooleanField(default=False)),
                (
                    "acknowledged_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("is_resolved", models.BooleanField(default=False)),
                (
                    "resolved_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True, null=True)),
                ("recommended_action", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "financial_alerts",
                "ordering": ["-severity", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FinancialBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("currency", models.CharField(default="SAR", max_length=3)),
                ("budget_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "actual_spend",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "revised_budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("utilization_percent", models.FloatField(default=0.0)),
                (
                    "variance_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("variance_percent", models.FloatField(default=0.0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("on_track", "On Track"),
                            ("at_risk", "At Risk"),
                            ("overrun", "Overrun"),
                            ("underutilized", "Underutilized"),
                        ],
                        default="on_track",
                        max_length=20,
                    ),
                ),
                (
                    "projected_final_spend",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("overrun_risk_percent", models.FloatField(default=0.0)),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "approved_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("approval_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "financial_budgets",
                "ordering": ["-period_start"],
            },
        ),
        migrations.CreateModel(
            name="FinancialNarrative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "narrative_type",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly Summary"),
                            ("quarterly", "Quarterly Summary"),
                            ("custom", "Custom Period"),
                        ],
                        default="monthly",
                        max_length=30,
                    ),
                ),
                ("narrative_text", models.TextField()),
                ("executive_summary", models.TextField(blank=True, null=True)),
                ("trends", models.JSONField(default=dict)),
                ("risks", models.JSONField(default=dict)),
                ("anomalies", models.JSONField(default=dict)),
                ("recommendations", models.JSONField(default=dict)),
                (
                    "total_spend",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("invoice_count", models.IntegerField(default=0)),
                ("vendor_count", models.IntegerField(default=0)),
                ("top_categories", models.JSONField(default=dict)),
                ("top_vendors", models.JSONField(default=dict)),
                ("overall_risk_score", models.FloatField(default=0.0)),
                ("anomaly_count", models.IntegerField(default=0)),
                ("duplicate_risk_count", models.IntegerField(default=0)),
                (
                    "generation_method",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI GPT"),
                            ("rule_based", "Rule-Based"),
                            ("hybrid", "Hybrid"),
                            ("manual", "Manual Analysis"),
                        ],
                        default="hybrid",
                        max_length=50,
                    ),
                ),
                ("confidence_score", models.FloatField(default=0.8)),
                ("data_completeness_percent", models.FloatField(default=100.0)),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "published_to",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("version", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "financial_narratives",
                "ordering": ["-period_start"],
            },
        ),
        migrations.CreateModel(
            name="SpendCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("month", models.DateField()),
                (
                    "monthly_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("invoice_count", models.IntegerField(default=0)),
                ("vendor_count", models.IntegerField(default=0)),
                ("currency", models.CharField(default="SAR", max_length=3)),
                (
                    "previous_month_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("trend_percent", models.FloatField(default=0.0)),
                (
                    "ytd_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("top_vendor", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "top_vendor_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "spend_categories",
                "ordering": ["-month", "-monthly_amount"],
            },
        ),
        migrations.CreateModel(
            name="VendorRisk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("vendor_name", models.CharField(max_length=255)),
                (
                    "vendor_tax_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("total_invoices", models.IntegerField(default=0)),
                ("duplicate_suspicion_count", models.IntegerField(default=0)),
                ("anomaly_count", models.IntegerField(default=0)),
                ("violation_count", models.IntegerField(default=0)),
                ("compliance_failure_count", models.IntegerField(default=0)),
                ("risk_score", models.IntegerField(default=0)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                ("risk_factors", models.JSONField(blank=True, null=True)),
                ("historical_issues", models.JSONField(blank=True, null=True)),
                ("last_analyzed_at", models.DateTimeField(blank=True, null=True)),
                ("last_violation_at", models.DateTimeField(blank=True, null=True)),
                ("last_anomaly_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "vendor_risks",
                "ordering": ["-risk_score", "-anomaly_count"],
            },
        ),
        migrations.CreateModel(
            name="VendorSpendMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_spend",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("invoice_count", models.IntegerField(default=0)),
                (
                    "average_invoice",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("currency", models.CharField(default="SAR", max_length=3)),
                (
                    "current_month_spend",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "previous_month_spend",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "ytd_spend",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("month_over_month_growth", models.FloatField(default=0.0)),
                (
                    "spending_velocity",
                    models.CharField(
                        choices=[
                            ("stable", "Stable"),
                            ("growing", "Growing"),
                            ("declining", "Declining"),
                            ("volatile", "Volatile"),
                        ],
                        default="stable",
                        max_length=20,
                    ),
                ),
                ("anomaly_growth_rate", models.FloatField(default=0.0)),
                (
                    "highest_invoice_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("highest_invoice_date", models.DateField(blank=True, null=True)),
                ("cost_concentration", models.FloatField(default=0.0)),
                ("is_critical_vendor", models.BooleanField(default=False)),
                (
                    "vendor_financial_health",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "vendor_spend_metrics",
            },
        ),
        migrations.AddField(
            model_name="extracteddata",
            name="anomaly_flags",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="extracteddata",
            name="anomaly_score",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="extracteddata",
            name="cross_document_findings_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="extracteddata",
            name="duplicate_matched_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="duplicate_matches",
                to="documents.extracteddata",
            ),
        ),
        migrations.AddField(
            model_name="extracteddata",
            name="duplicate_score",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="extracteddata",
            name="phase4_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="extracteddata",
            name="vendor_risk_level",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="extracteddata",
            name="vendor_risk_score",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddIndex(
            model_name="extracteddata",
            index=models.Index(
                fields=["vendor_name"], name="extracted_d_vendor__240120_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="extracteddata",
            index=models.Index(
                fields=["invoice_date"], name="extracted_d_invoice_ff5817_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="extracteddata",
            index=models.Index(
                fields=["total_amount"], name="extracted_d_total_a_c5bc95_idx"
            ),
        ),
        migrations.AddField(
            model_name="anomalylog",
            name="extracted_data",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="anomaly_logs",
                to="documents.extracteddata",
            ),
        ),
        migrations.AddField(
            model_name="anomalylog",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="anomaly_logs",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="cashflowforecast",
            name="extracted_data",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cash_flow_forecasts",
                to="documents.extracteddata",
            ),
        ),
        migrations.AddField(
            model_name="cashflowforecast",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cash_flow_forecasts",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="crossdocumentfinding",
            name="extracted_data",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cross_document_findings",
                to="documents.extracteddata",
            ),
        ),
        migrations.AddField(
            model_name="crossdocumentfinding",
            name="matched_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matched_by_findings",
                to="documents.extracteddata",
            ),
        ),
        migrations.AddField(
            model_name="crossdocumentfinding",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cross_document_findings",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="crossdocumentfinding",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_cross_doc_findings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="financialalert",
            name="extracted_data",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="financial_alerts",
                to="documents.extracteddata",
            ),
        ),
        migrations.AddField(
            model_name="financialalert",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="financial_alerts",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="financialbudget",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="financial_budgets",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="financialnarrative",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="financial_narratives",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="financialnarrative",
            name="previous_narrative",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next_version",
                to="documents.financialnarrative",
            ),
        ),
        migrations.AddField(
            model_name="spendcategory",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spend_categories",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="vendorrisk",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vendor_risks",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="vendorspendmetrics",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vendor_spend_metrics",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="vendorspendmetrics",
            name="vendor_risk",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spend_metrics",
                to="documents.vendorrisk",
            ),
        ),
        migrations.AddIndex(
            model_name="anomalylog",
            index=models.Index(
                fields=["extracted_data"], name="anomaly_log_extract_04270c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anomalylog",
            index=models.Index(
                fields=["organization"], name="anomaly_log_organiz_bcb039_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anomalylog",
            index=models.Index(
                fields=["anomaly_type"], name="anomaly_log_anomaly_d23e69_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anomalylog",
            index=models.Index(
                fields=["severity"], name="anomaly_log_severit_9bae01_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anomalylog",
            index=models.Index(
                fields=["confidence_score"], name="anomaly_log_confide_59944b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anomalylog",
            index=models.Index(
                fields=["is_confirmed"], name="anomaly_log_is_conf_86f5c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cashflowforecast",
            index=models.Index(
                fields=["organization", "projected_payment_30d"],
                name="cash_flow_f_organiz_52416e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cashflowforecast",
            index=models.Index(
                fields=["organization", "projected_payment_60d"],
                name="cash_flow_f_organiz_8cac0d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cashflowforecast",
            index=models.Index(
                fields=["organization", "projected_payment_90d"],
                name="cash_flow_f_organiz_8a57e2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cashflowforecast",
            index=models.Index(
                fields=["currency"], name="cash_flow_f_currenc_9b6ae6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cashflowforecast",
            index=models.Index(
                fields=["payment_status"], name="cash_flow_f_payment_635a77_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crossdocumentfinding",
            index=models.Index(
                fields=["extracted_data"], name="cross_docum_extract_d61c9d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crossdocumentfinding",
            index=models.Index(
                fields=["organization"], name="cross_docum_organiz_c0b974_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crossdocumentfinding",
            index=models.Index(
                fields=["finding_type"], name="cross_docum_finding_05e9c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crossdocumentfinding",
            index=models.Index(
                fields=["severity"], name="cross_docum_severit_d9b830_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crossdocumentfinding",
            index=models.Index(fields=["status"], name="cross_docum_status_237dd4_idx"),
        ),
        migrations.AddIndex(
            model_name="crossdocumentfinding",
            index=models.Index(
                fields=["is_resolved"], name="cross_docum_is_reso_22ac66_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crossdocumentfinding",
            index=models.Index(
                fields=["matched_document"], name="cross_docum_matched_487e27_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crossdocumentfinding",
            index=models.Index(
                fields=["confidence_score"], name="cross_docum_confide_08ce1b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialalert",
            index=models.Index(
                fields=["organization", "-created_at"],
                name="financial_a_organiz_52c6ad_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="financialalert",
            index=models.Index(
                fields=["severity"], name="financial_a_severit_413155_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialalert",
            index=models.Index(
                fields=["alert_type"], name="financial_a_alert_t_07f6bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialalert",
            index=models.Index(
                fields=["is_resolved"], name="financial_a_is_reso_6726e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialalert",
            index=models.Index(
                fields=["is_acknowledged"], name="financial_a_is_ackn_03a992_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialbudget",
            index=models.Index(
                fields=["organization", "period_start"],
                name="financial_b_organiz_949993_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="financialbudget",
            index=models.Index(fields=["status"], name="financial_b_status_61ea2e_idx"),
        ),
        migrations.AddIndex(
            model_name="financialbudget",
            index=models.Index(
                fields=["category"], name="financial_b_categor_62abd3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialnarrative",
            index=models.Index(
                fields=["organization", "period_start"],
                name="financial_n_organiz_59b829_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="financialnarrative",
            index=models.Index(
                fields=["narrative_type"], name="financial_n_narrati_7ab06a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialnarrative",
            index=models.Index(
                fields=["is_published"], name="financial_n_is_publ_9f5bee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="spendcategory",
            index=models.Index(
                fields=["organization", "month"], name="spend_categ_organiz_6e6da0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="spendcategory",
            index=models.Index(
                fields=["organization", "category"],
                name="spend_categ_organiz_df30d3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="spendcategory",
            index=models.Index(fields=["month"], name="spend_categ_month_b8a3db_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="spendcategory",
            unique_together={("organization", "category", "month")},
        ),
        migrations.AddIndex(
            model_name="vendorrisk",
            index=models.Index(
                fields=["organization"], name="vendor_risk_organiz_dae794_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendorrisk",
            index=models.Index(
                fields=["vendor_name"], name="vendor_risk_vendor__eacd2f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendorrisk",
            index=models.Index(
                fields=["risk_level"], name="vendor_risk_risk_le_12ca82_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendorrisk",
            index=models.Index(
                fields=["risk_score"], name="vendor_risk_risk_sc_548717_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vendorrisk",
            unique_together={("organization", "vendor_name")},
        ),
        migrations.AddIndex(
            model_name="vendorspendmetrics",
            index=models.Index(
                fields=["organization", "-total_spend"],
                name="vendor_spen_organiz_75522a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vendorspendmetrics",
            index=models.Index(
                fields=["spending_velocity"], name="vendor_spen_spendin_bf40a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendorspendmetrics",
            index=models.Index(
                fields=["is_critical_vendor"], name="vendor_spen_is_crit_04f8d3_idx"
            ),
        ),
    ]
