# Generated by Django 5.0.1 on 2026-03-07 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0005_anomalylog_cashflowforecast_crossdocumentfinding_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="extracteddata",
            name="extraction_provider",
            field=models.CharField(default="unknown", max_length=50),
        ),
        migrations.AddField(
            model_name="extracteddata",
            name="is_fallback",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="extracteddata",
            name="review_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="extracteddata",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="extracteddata",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_extractions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("validated", "Validated"),
                    ("pending_review", "Pending Review"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
