# Generated by Django 5.0.1 on 2026-03-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0006_is_fallback_pending_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocrevidence",
            name="extracted_currency",
            field=models.CharField(
                blank=True,
                default="SAR",
                help_text="Currency Code",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ocrevidence",
            name="extracted_customer_address",
            field=models.TextField(blank=True, help_text="Customer Address", null=True),
        ),
        migrations.AddField(
            model_name="ocrevidence",
            name="extracted_customer_name",
            field=models.CharField(
                blank=True, help_text="Customer Name", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="ocrevidence",
            name="extracted_due_date",
            field=models.DateField(blank=True, help_text="Due Date", null=True),
        ),
        migrations.AddField(
            model_name="ocrevidence",
            name="extracted_invoice_date",
            field=models.DateField(blank=True, help_text="Invoice Date", null=True),
        ),
        migrations.AddField(
            model_name="ocrevidence",
            name="extracted_items",
            field=models.JSONField(blank=True, help_text="Line items array", null=True),
        ),
        migrations.AddField(
            model_name="ocrevidence",
            name="extracted_vendor_address",
            field=models.TextField(blank=True, help_text="Vendor Address", null=True),
        ),
        migrations.AddField(
            model_name="ocrevidence",
            name="extracted_vendor_name",
            field=models.CharField(
                blank=True, help_text="Vendor/Supplier Name", max_length=255, null=True
            ),
        ),
    ]
