# Generated by Django 5.0.1 on 2026-03-07 14:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_organization_logo"),
        ("documents", "0007_ocrevidence_extracted_currency_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceAuditReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("generated", "Generated"),
                            ("reviewed", "Reviewed"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("pending_review", "Pending Review"),
                        ],
                        default="generated",
                        max_length=20,
                    ),
                ),
                (
                    "report_number",
                    models.CharField(
                        help_text="Unique audit report identifier", max_length=20
                    ),
                ),
                ("upload_date", models.DateTimeField(blank=True, null=True)),
                ("ocr_engine", models.CharField(blank=True, max_length=50, null=True)),
                ("ocr_confidence_score", models.IntegerField(default=0)),
                (
                    "processing_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "extracted_invoice_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("extracted_issue_date", models.DateField(blank=True, null=True)),
                ("extracted_due_date", models.DateField(blank=True, null=True)),
                (
                    "extracted_vendor_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("extracted_vendor_address", models.TextField(blank=True, null=True)),
                (
                    "extracted_vendor_tin",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "extracted_customer_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("extracted_customer_address", models.TextField(blank=True, null=True)),
                (
                    "extracted_customer_tin",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "line_items_json",
                    models.JSONField(
                        blank=True,
                        help_text="Array of {product, description, quantity, unit_price, discount, total}",
                        null=True,
                    ),
                ),
                (
                    "subtotal_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "vat_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="SAR",
                        help_text="Currency code (SAR, USD, etc.)",
                        max_length=10,
                    ),
                ),
                (
                    "validation_results_json",
                    models.JSONField(
                        blank=True,
                        help_text="Results for each validation check: {invoice_number: pass/warning/fail, vendor: ..., customer: ..., items: ..., total_match: ..., vat: ...}",
                        null=True,
                    ),
                ),
                (
                    "compliance_checks_json",
                    models.JSONField(
                        blank=True, help_text="Array of compliance findings", null=True
                    ),
                ),
                (
                    "duplicate_score",
                    models.IntegerField(
                        default=0, help_text="Duplicate probability 0-100"
                    ),
                ),
                (
                    "duplicate_matched_documents_json",
                    models.JSONField(
                        blank=True,
                        help_text="Array of matched duplicate documents",
                        null=True,
                    ),
                ),
                (
                    "duplicate_status",
                    models.CharField(
                        choices=[
                            ("no_duplicate", "No Duplicate Detected"),
                            ("low_risk", "Low Duplicate Risk"),
                            ("medium_risk", "Medium Duplicate Risk"),
                            ("high_risk", "High Duplicate Risk"),
                            ("confirmed_duplicate", "Confirmed Duplicate"),
                        ],
                        default="no_duplicate",
                        max_length=50,
                    ),
                ),
                (
                    "anomaly_score",
                    models.IntegerField(
                        default=0, help_text="Anomaly probability 0-100"
                    ),
                ),
                (
                    "anomaly_status",
                    models.CharField(
                        choices=[
                            ("no_anomaly", "No Anomaly Detected"),
                            ("low_anomaly", "Low Anomaly Risk"),
                            ("medium_anomaly", "Medium Anomaly Risk"),
                            ("high_anomaly", "High Anomaly Risk"),
                            ("critical_anomaly", "Critical Anomaly"),
                        ],
                        default="no_anomaly",
                        max_length=50,
                    ),
                ),
                (
                    "anomaly_explanation",
                    models.TextField(
                        blank=True,
                        help_text="Description of detected anomalies",
                        null=True,
                    ),
                ),
                (
                    "anomaly_reasons_json",
                    models.JSONField(
                        blank=True, help_text="Array of anomaly reasons", null=True
                    ),
                ),
                (
                    "risk_score",
                    models.IntegerField(
                        default=0, help_text="Overall risk score 0-100"
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                (
                    "risk_factors_json",
                    models.JSONField(
                        blank=True,
                        help_text="Array of identified risk factors",
                        null=True,
                    ),
                ),
                (
                    "ai_summary",
                    models.TextField(
                        blank=True,
                        help_text="AI-generated summary in English",
                        null=True,
                    ),
                ),
                (
                    "ai_summary_ar",
                    models.TextField(
                        blank=True,
                        help_text="AI-generated summary in Arabic",
                        null=True,
                    ),
                ),
                (
                    "ai_findings",
                    models.TextField(
                        blank=True,
                        help_text="AI analysis of problems and issues",
                        null=True,
                    ),
                ),
                (
                    "ai_findings_ar",
                    models.TextField(
                        blank=True, help_text="AI analysis in Arabic", null=True
                    ),
                ),
                (
                    "ai_review_required",
                    models.BooleanField(
                        default=False, help_text="Whether AI recommends manual review"
                    ),
                ),
                (
                    "recommendation",
                    models.CharField(
                        choices=[
                            ("approve", "Approve"),
                            ("manual_review", "Manual Review Required"),
                            ("reject", "Reject"),
                        ],
                        default="manual_review",
                        max_length=20,
                    ),
                ),
                (
                    "recommendation_reason",
                    models.TextField(
                        blank=True, help_text="Reason for the recommendation", null=True
                    ),
                ),
                (
                    "recommendation_reason_ar",
                    models.TextField(
                        blank=True, help_text="Reason in Arabic", null=True
                    ),
                ),
                (
                    "audit_trail_json",
                    models.JSONField(
                        blank=True,
                        help_text="Timeline of all processing steps",
                        null=True,
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                (
                    "full_report_json",
                    models.JSONField(
                        blank=True,
                        help_text="Complete report as JSON for export and storage",
                        null=True,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_audit_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_report",
                        to="documents.document",
                    ),
                ),
                (
                    "extracted_data",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_report",
                        to="documents.extracteddata",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_audit_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ocr_evidence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_reports",
                        to="documents.ocrevidence",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_audit_reports",
                        to="core.organization",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_audit_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "invoice_audit_reports",
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["document"], name="invoice_aud_documen_c3a710_idx"
                    ),
                    models.Index(
                        fields=["extracted_data"], name="invoice_aud_extract_83b8a8_idx"
                    ),
                    models.Index(
                        fields=["organization"], name="invoice_aud_organiz_215e91_idx"
                    ),
                    models.Index(
                        fields=["status"], name="invoice_aud_status_4461d1_idx"
                    ),
                    models.Index(
                        fields=["risk_level"], name="invoice_aud_risk_le_79215c_idx"
                    ),
                    models.Index(
                        fields=["generated_at"], name="invoice_aud_generat_b6f406_idx"
                    ),
                ],
            },
        ),
    ]
