# Generated by Django 5.0.1 on 2026-03-10 15:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_organization_created_by_organizationmember_and_more"),
        ("documents", "0008_invoiceauditreport"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="content_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="extracteddata",
            name="customer_tax_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="extracteddata",
            name="raw_json",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="extracteddata",
            name="subtotal_amount",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="extracteddata",
            name="vendor_tax_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "commercial_registration",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("vat_number", models.CharField(blank=True, max_length=20, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_vendors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendors",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "vendors",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "customer_vat_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "invoice_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("currency", models.CharField(default="SAR", max_length=10)),
                (
                    "subtotal_amount",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "vat_amount",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "cost_center",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("raw_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accounting_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_records",
                        to="documents.account",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_invoice_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "budget",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_records",
                        to="documents.financialbudget",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_invoice_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer_organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_invoice_records",
                        to="core.organization",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_records",
                        to="documents.document",
                    ),
                ),
                (
                    "extracted_data",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_record",
                        to="documents.extracteddata",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_records",
                        to="core.organization",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice_records",
                        to="documents.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "invoice_records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceLineItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("line_number", models.PositiveIntegerField(default=1)),
                ("description", models.CharField(max_length=500)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=6, default=0, max_digits=18),
                ),
                (
                    "line_total",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                ("raw_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="documents.invoicerecord",
                    ),
                ),
            ],
            options={
                "db_table": "invoice_line_items",
                "ordering": ["line_number"],
                "indexes": [
                    models.Index(
                        fields=["invoice"], name="invoice_lin_invoice_d51b23_idx"
                    ),
                    models.Index(
                        fields=["description"], name="invoice_lin_descrip_87fcae_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="invoicelineitem",
            constraint=models.UniqueConstraint(
                fields=("invoice", "line_number"), name="uniq_invoice_line_number"
            ),
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(
                fields=["organization"], name="vendors_organiz_f8fcc3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(
                fields=["vat_number"], name="vendors_vat_num_676c1c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(fields=["name"], name="vendors_name_a8eecc_idx"),
        ),
        migrations.AddConstraint(
            model_name="vendor",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("vat_number__isnull", False),
                    models.Q(("vat_number", ""), _negated=True),
                ),
                fields=("organization", "vat_number"),
                name="uniq_vendor_org_vat",
            ),
        ),
        migrations.AddIndex(
            model_name="invoicerecord",
            index=models.Index(
                fields=["organization"], name="invoice_rec_organiz_71bd39_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoicerecord",
            index=models.Index(
                fields=["vendor"], name="invoice_rec_vendor__fcc8d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoicerecord",
            index=models.Index(
                fields=["invoice_number"], name="invoice_rec_invoice_3475c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoicerecord",
            index=models.Index(
                fields=["issue_date"], name="invoice_rec_issue_d_a9524a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoicerecord",
            index=models.Index(
                fields=["total_amount"], name="invoice_rec_total_a_43b327_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoicerecord",
            index=models.Index(
                fields=["approval_status"], name="invoice_rec_approva_5a7850_idx"
            ),
        ),
    ]
