# Generated by Django 5.0.1 on 2026-03-10 19:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_organization_created_by_organizationmember_and_more"),
        (
            "documents",
            "0009_document_content_hash_extracteddata_customer_tax_id_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("web_upload", "Web Upload"),
                            ("api_upload", "API Upload"),
                            ("background_task", "Background Task"),
                            ("ocr_signal", "OCR Signal"),
                            ("re_audit", "Re-Audit"),
                        ],
                        default="web_upload",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("published", "Published"),
                            ("failed", "Failed"),
                        ],
                        default="processing",
                        max_length=20,
                    ),
                ),
                (
                    "current_stage",
                    models.CharField(
                        choices=[
                            ("upload_file", "Upload File"),
                            ("create_audit_session", "Create AuditSession"),
                            ("save_document", "Save Document"),
                            ("ai_extraction", "AI Extraction"),
                            ("normalization", "Normalization"),
                            ("validation", "Validation"),
                            ("compliance_engine", "Compliance Engine"),
                            ("risk_score", "Risk Score"),
                            ("findings", "Findings"),
                            ("ai_executive_summary", "AI Executive Summary"),
                            ("publish_to_dashboard", "Publish to Dashboard"),
                        ],
                        default="create_audit_session",
                        max_length=40,
                    ),
                ),
                ("file_name", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "content_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "customer_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "customer_tax_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("stages_json", models.JSONField(blank=True, default=dict)),
                ("dashboard_payload", models.JSONField(blank=True, default=dict)),
                ("last_error", models.TextField(blank=True, null=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_sessions",
                        to="documents.document",
                    ),
                ),
                (
                    "extracted_data",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_sessions",
                        to="documents.extracteddata",
                    ),
                ),
                (
                    "invoice_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_sessions",
                        to="documents.invoicerecord",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_sessions",
                        to="core.organization",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="started_audit_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_sessions",
                        to="documents.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "audit_sessions",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["organization"], name="audit_sessi_organiz_bafd82_idx"
                    ),
                    models.Index(
                        fields=["status"], name="audit_sessi_status_90caa9_idx"
                    ),
                    models.Index(
                        fields=["source"], name="audit_sessi_source_77b2b1_idx"
                    ),
                    models.Index(
                        fields=["current_stage"], name="audit_sessi_current_0642b1_idx"
                    ),
                    models.Index(
                        fields=["document"], name="audit_sessi_documen_3e9f9c_idx"
                    ),
                ],
            },
        ),
    ]
