# Generated by Django 5.0.1 on 2026-01-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="name_ar",
            field=models.CharField(
                blank=True, help_text="اسم الشركة بالعربية", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="vat_applicable",
            field=models.BooleanField(
                default=False, help_text="هل تنطبق ضريبة القيمة المضافة على هذه الشركة؟"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="vat_number",
            field=models.CharField(
                blank=True,
                help_text="رقم التسجيل في ضريبة القيمة المضافة",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="vat_validated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="تاريخ التحقق من رقم ضريبة القيمة المضافة",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="vat_validation_message",
            field=models.TextField(
                blank=True,
                help_text="رسالة التحقق من رقم ضريبة القيمة المضافة",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="vat_validation_status",
            field=models.CharField(
                choices=[
                    ("not_validated", "لم يتم التحقق - Not Validated"),
                    ("valid", "صالح - Valid"),
                    ("invalid", "غير صالح - Invalid"),
                    ("not_required", "غير مطلوب - Not Required"),
                ],
                default="not_validated",
                help_text="حالة التحقق من رقم ضريبة القيمة المضافة",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="zatca_enabled",
            field=models.BooleanField(
                default=False, help_text="تفعيل التحقق من هيئة الزكاة والضريبة والجمارك"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="zatca_verification_scope",
            field=models.CharField(
                choices=[
                    ("disabled", "معطل - Disabled"),
                    ("verification_only", "التحقق فقط - Verification Only"),
                ],
                default="disabled",
                help_text="نطاق التحقق من ZATCA",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="company_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("government", "Government - حكومي"),
                    ("semi_government", "Semi-Government - شبه حكومي"),
                    ("private", "Private - خاص"),
                    ("sme", "SME - منشأة صغيرة ومتوسطة"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="country",
            field=models.CharField(
                choices=[
                    ("SA", "Saudi Arabia - المملكة العربية السعودية"),
                    ("AE", "United Arab Emirates - الإمارات العربية المتحدة"),
                    ("BH", "Bahrain - البحرين"),
                    ("KW", "Kuwait - الكويت"),
                    ("OM", "Oman - عمان"),
                    ("QA", "Qatar - قطر"),
                ],
                help_text="البلد",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(help_text="اسم الشركة", max_length=255),
        ),
    ]
