# Generated by Django 5.0.1 on 2026-01-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_add_vat_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="logo",
            field=models.ImageField(
                blank=True, help_text="شعار الشركة", null=True, upload_to="org_logos/"
            ),
        ),
    ]
